// Code generated by Fire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/fire/cmd/fire
//go:build !fireinject
// +build !fireinject

package main

// Injectors from fire.go:

func injectedMessage() string {
	s := provideS()
	string2 := s.Foo
	return string2
}

func injectedMessagePtr() *string {
	s := provideS()
	string2 := &s.Foo
	return string2
}
