// This is a sample header file.
//
// Code generated by Fire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/fire/cmd/fire
//go:build !fireinject
// +build !fireinject

package main

// Injectors from fire.go:

func injectFoo() Foo {
	foo := provideFoo()
	return foo
}
