// Code generated by Fire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/fire/cmd/fire
//go:build !fireinject
// +build !fireinject

package main

// Injectors from fire.go:

func injectFooBar() FooBar {
	bar := provideBar()
	fooBar := provideFooBar(bar, bar)
	return fooBar
}
