// Code generated by Fire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/fire/cmd/fire
//go:build !fireinject
// +build !fireinject

package main

import (
	"example.com/bar"
)

// Injectors from fire.go:

func injectedMessage() string {
	string2 := _fireStringValue
	return string2
}

var (
	_fireStringValue = bar.PublicMsg
)
