// Code generated by Fire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/myyrakle/fire/cmd/fire
//go:build !fireinject
// +build !fireinject

package main

// Injectors from fire.go:

func inject(foo Foo) *Bar {
	bar := NewBar(foo)
	return bar
}
