// Code generated by Fire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/fire/cmd/fire
//go:build !fireinject
// +build !fireinject

package main

import (
	"fmt"

	"example.com/bar"
	"example.com/baz"
	"example.com/foo"
)

// Injectors from fire.go:

func newBazService() *baz.Service {
	config := _fireConfigValue
	fooConfig := config.Foo
	service := foo.New(fooConfig)
	barConfig := config.Bar
	barService := bar.New(barConfig, service)
	bazService := &baz.Service{
		Foo: service,
		Bar: barService,
	}
	return bazService
}

var (
	_fireConfigValue = &baz.Config{
		Foo: &foo.Config{1},
		Bar: &bar.Config{2},
	}
)

// fire.go:

func main() {
	svc := newBazService()
	fmt.Println(svc.String())
}
