// Code generated by Fire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/fire/cmd/fire
//go:build !fireinject
// +build !fireinject

package main

import (
	"example.com/foo"
)

// Injectors from fire.go:

func injectFooer() foo.Fooer {
	bar := provideBar()
	return bar
}
