// Code generated by Fire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/fire/cmd/fire
//go:build !fireinject
// +build !fireinject

package main

import (
	context2 "context"
)

// Injectors from fire.go:

func inject(contextContext context2.Context, arg struct{}) (context, error) {
	mainContext, err := provide(contextContext)
	if err != nil {
		return context{}, err
	}
	return mainContext, nil
}
