// Code generated by Fire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/myyrakle/fire/cmd/fire
//go:build !fireinject
// +build !fireinject

package main

import (
	"io"
	"strings"
)

// Injectors from fire.go:

func injectedReader() io.Reader {
	reader := _fireReaderValue
	return reader
}

var (
	_fireReaderValue = strings.NewReader("hello world")
)
