// Code generated by Fire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/fire/cmd/fire
//go:build !fireinject
// +build !fireinject

package main

import (
	"fmt"
)

// Injectors from fire.go:

func injectStringer(s MyString) fmt.Stringer {
	return s
}
