// Code generated by Fire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/myyrakle/fire/cmd/fire
//go:build !fireinject
// +build !fireinject

package main

import (
	"io"
	"os"
)

// Injectors from fire.go:

func inject() io.Writer {
	file := _fireFileValue
	return file
}

var (
	_fireFileValue = os.Stdout
)
