// Code generated by Fire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/fire/cmd/fire
//go:build !fireinject
// +build !fireinject

package main

// Injectors from fire.go:

func injectFoo() (Foo, error) {
	foo, err := provideFoo()
	if err != nil {
		return 0, err
	}
	return foo, nil
}
