// Code generated by Fire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/myyrakle/fire/cmd/fire
//go:build !fireinject
// +build !fireinject

package main

import (
	"fmt"
)

// Injectors from foo.go:

func injectedMessage() string {
	string2 := provideMessage()
	return string2
}

// foo.go:

func main() {
	fmt.Println(injectedMessage())
}

// provideMessage provides a friendly user greeting.
func provideMessage() string {
	return "Hello, World!"
}
