// Code generated by Fire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/fire/cmd/fire
//go:build !fireinject
// +build !fireinject

package main

// Injectors from fire.go:

func injectedMessage() Foo {
	foo := _fireFooValue
	return foo
}

var (
	_fireFooValue = Foo("Hello, World!")
)
