// Code generated by Fire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/myyrakle/fire/cmd/fire
//go:build !fireinject
// +build !fireinject

package main

// Injectors from fire.go:

func injectFoo() Foo {
	foo := _fireFooValue
	return foo
}

var (
	_fireFooValue = Foo{X: 42}
)
