// Code generated by Fire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/fire/cmd/fire
//go:build !fireinject
// +build !fireinject

package main

import (
	"example.com/bar"

	_ "example.com/anon1"

	_ "example.com/anon2"
)

// Injectors from fire.go:

func injectFooBar() FooBar {
	foo := provideFoo()
	barBar := bar.ProvideBar()
	fooBar := provideFooBar(foo, barBar)
	return fooBar
}
