// Code generated by Fire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/myyrakle/fire/cmd/fire
//go:build !fireinject
// +build !fireinject

package main

// Injectors from fire.go:

func injectFooBar() *FooBar {
	foo := provideFoo()
	bar := provideBar()
	fooBar := &FooBar{
		Foo: foo,
		Bar: bar,
	}
	return fooBar
}

func injectEmptyStruct() *Empty {
	empty := &Empty{}
	return empty
}
